In [2]:
#Section A: Data Structures & Control Structures
#1.List operations

# Create list
nums = [10, 20, 30, 40, 50]

# append
nums.append(60)
print("After append:", nums)

# extend
nums.extend([70, 80])
print("After extend:", nums)

# insert
nums.insert(2, 25)
print("After insert:", nums)

# remove
nums.remove(40)
print("After remove:", nums)

# pop
nums.pop()
print("After pop:", nums)

# index
print("Index of 30:", nums.index(30))

# count
print("Count of 20:", nums.count(20))

# sort
nums.sort()
print("Sorted list:", nums)

# reverse
nums.reverse()
print("Reversed list:", nums)

# clear
nums.clear()
print("After clear:", nums)

After append: [10, 20, 30, 40, 50, 60]
After extend: [10, 20, 30, 40, 50, 60, 70, 80]
After insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove: [10, 20, 25, 30, 50, 60, 70, 80]
After pop: [10, 20, 25, 30, 50, 60, 70]
Index of 30: 3
Count of 20: 1
Sorted list: [10, 20, 25, 30, 50, 60, 70]
Reversed list: [70, 60, 50, 30, 25, 20, 10]
After clear: []


In [4]:
#2Tuple immutability
students = ("Aparna", "Rahul", "Sneha")

students[1] = "Kiran"

TypeError: 'tuple' object does not support item assignment

In [5]:
#3.Set with duplicates
s = {1, 2, 3, 2, 4, 1, 5}
print(s)

{1, 2, 3, 4, 5}


In [6]:
#4.Dictionary update
person = {
    "name": "Aparna",
    "age": 21,
    "city": "Mangalore"
}

# update age
person["age"] = 22

# add new key
person["email"] = "aparna@gmail.com"

print(person)

{'name': 'Aparna', 'age': 22, 'city': 'Mangalore', 'email': 'aparna@gmail.com'}


In [7]:
#5.Voting eligibility
age = 20

if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Eligible to vote


In [8]:
#6.Grade System
marks = 82

if marks >= 90:
    print("A")
elif marks >= 75:
    print("B")
elif marks >= 50:
    print("C")
else:
    print("Fail")

B


In [9]:
#7.Positive, even, zero, negative check
num = 4

if num > 0:
    print("Positive number")
    if num % 2 == 0:
        print("It is also even")
    else:
        print("It is odd")
elif num == 0:
    print("Number is zero")
else:
    print("Negative number")

Positive number
It is also even


In [10]:
##Section B: NumPy
import numpy as np

In [11]:
#8.create arrays
# scalar
scalar = np.array(5)
print("Scalar:", scalar)

# 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D array:", arr1)

# 2D array (2x3)
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60]])
print("2D array:\n", arr2)

Scalar: 5
1D array: [1 2 3 4 5]
2D array:
 [[10 20 30]
 [40 50 60]]


In [12]:
#9.Random 4x4 array
rand_arr = np.random.randint(0, 101, size=(4, 4))
print(rand_arr)

[[ 29   4  20  84]
 [ 93  36  65  53]
 [  3  21  71  53]
 [ 23  27  35 100]]


In [13]:
#10.NumPy → Pandas DataFrame
import pandas as pd

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

df = pd.DataFrame(arr, columns=['A', 'B', 'C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [14]:
##Section C: Pandas
#11.Create DataFrame
data = {
    "Name": ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"],
    "Age": [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
    "City": ["Mangalore", "Bangalore", "Delhi", "Mumbai", "Chennai",
             "Kolkata", "Hyderabad", "Pune", "Goa", "Jaipur"],
    "Salary": [25000, 30000, None, 28000, 35000, None, 40000, 32000, 30000, 29000]
}

df = pd.DataFrame(data)

In [16]:
print(df.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None


In [17]:
print(df.describe())

            Age        Salary
count  10.00000      8.000000
mean   25.50000  31125.000000
std     3.02765   4611.708701
min    21.00000  25000.000000
25%    23.25000  28750.000000
50%    25.50000  30000.000000
75%    27.75000  32750.000000
max    30.00000  40000.000000


In [18]:
print(df[["Name", "City"]])

  Name       City
0    A  Mangalore
1    B  Bangalore
2    C      Delhi
3    D     Mumbai
4    E    Chennai
5    F    Kolkata
6    G  Hyderabad
7    H       Pune
8    I        Goa
9    J     Jaipur


In [19]:
df = df.drop("City", axis=1)
print(df)

  Name  Age   Salary
0    A   21  25000.0
1    B   22  30000.0
2    C   23      NaN
3    D   24  28000.0
4    E   25  35000.0
5    F   26      NaN
6    G   27  40000.0
7    H   28  32000.0
8    I   29  30000.0
9    J   30  29000.0


In [20]:
mean_salary = df["Salary"].mean()
df["Salary"].fillna(mean_salary, inplace=True)
print(df)

  Name  Age   Salary
0    A   21  25000.0
1    B   22  30000.0
2    C   23  31125.0
3    D   24  28000.0
4    E   25  35000.0
5    F   26  31125.0
6    G   27  40000.0
7    H   28  32000.0
8    I   29  30000.0
9    J   30  29000.0


/tmp/ipython-input-4029192078.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(mean_salary, inplace=True)


In [21]:
df = df.drop_duplicates()
print(df)


  Name  Age   Salary
0    A   21  25000.0
1    B   22  30000.0
2    C   23  31125.0
3    D   24  28000.0
4    E   25  35000.0
5    F   26  31125.0
6    G   27  40000.0
7    H   28  32000.0
8    I   29  30000.0
9    J   30  29000.0
